name: metamgnn2
channels:
    - defaults
    - conda-forge
    - nvidia
    - pytorch
dependencies:
    - python = 3.6
    - torch = 1.4.0
    - torch-geometric 
    - torch-scatter 
    - torch-sparse 
    - scikit-learn 
    - tqdm 
    - rdkit
