name: metamgnn2
channels:
    - conda-forge
    - defaults
dependencies:
    - torch = 1.4.0
    - torch-geometric = 1.6.1
    - torch-scatter = 2.0.4
    - torch-sparse = 0.6.1
    - scikit-learn = 0.23.2
    - tqdm = 4.50.0
    - rdkit