name: metamgnn3
channels:
    - conda-forge
    - defaults
dependencies:
    - pip=19.3
    - python=3.6
    - pip:
      - rdkit-pypi
      - scikit-learn
      - scipy
      - torch==1.4.0+cu102
      - torch-cluster
      - torch-geometric
      - torch-scatter
      - torch-sparse
      - torch-spline-conv
      - tqdm
      
