name: metamgnn2
channels:
    - conda-forge
    - defaults
    - nvidia
    - pytorch
dependencies:
    - python=3.6
    - pytorch 1.4.0
    - torchvision
    - cudatoolkit=11.3
    - torchaudio
    - torch-geometric 
    - torch-scatter 
    - torch-sparse 
    - scikit-learn 
    - tqdm 
    - rdkit
